CREATE DATABASE IF NOT EXISTS traderbot;
USE traderbot;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(32) NOT NULL
);
